<?php
/**
 * Created by PhpStorm.
 * User: aymen
 * Date: 21/11/2018
 * Time: 10:58
 */

class Tv extends EquipementElectric
{
   private $type;

   private $resolution;

   private $son;

    function getNorme()
    {
        // TODO: Implement getNorme() method.
    }


    const SON_MAXIMAL = 10;
   const SON_MINIMAL = 0;
   const TVA = 18;
   const MIN_PRICE = 5;
   public function __construct(string $nom = "unknown", int $ns = 000000, string $marque = "LG", int $prix = 200, $type="LED",$resolution="FHD")
   {
       parent::__construct($nom, $ns, $marque, $prix);
       $this->resolution = $resolution;
       $this->type = $type;
       $this->son = 5;
       self::$nbVendu++;
   }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type): void
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getResolution()
    {
        return $this->resolution;
    }

    /**
     * @param mixed $resolution
     */
    public function setResolution($resolution): void
    {
        $this->resolution = $resolution;
    }

    public function afficheEquipement()
    {
        echo '<hr>Je suis une Télévision <hr>';
        parent::afficheEquipement();
        // TODO: Change the autogenerated stub
        echo "<br> Resolution : $this->resolution 
        <br> Type : $this->type<hr>    
        ";
    }

    public function muet() {
        $this->son = 0;
    }

    public function augmenterSon() {
        if ($this->son < self::SON_MAXIMAL)
               $this->son++;
    }

    public function diminuerSon() {
        if ($this->son > self::SON_MINIMAL)
               $this->son--;
    }

    public static function getNombre() {
          echo "<hr>Je suis la télé numéro : ".self::$nbVendu."<hr>" ;
    }

    public function getPrice()
    {
       echo "<hr>TV ";
       return ($this->prix * self::TVA) + self::MIN_PRICE;
    }

}